### ISSUE TITLE
Not able to build FW 28

### ISSUE THREAD

**Issue by mm-tkr** [WAGO/pfc300-firmware-sdk#1]
Hi,

I checked out the FW 28 and executed the steps `make builder`, `make init` and then `make get`.
Unfortunately the last step doesn't succeed. I get some MD5 mismatches for the following files:
- kernel-header
- u-boot
- boost
- host-go
- rootlesskit-dep

In case I fix them to the md5 hashes which are correct on my machine, I then end up with a different error.
I executed the `make bash` command following `ptxdist targetinstall pam lighttpd`. 
But again the kernel-header is making my life miserable:
```
-------------------------
target: kernel-header.get
-------------------------

finished target kernel-header.get

-----------------------------
target: kernel-header.extract
-----------------------------

extract: pkg_src=ptxproj/src/linux-6.6.15-rt22-w05.03.04-g9cbaa8e3b5c6.tgz
extract: pkg_extract_dir=ptxproj/platform-wago-pfc300/build-target/kernel-header-6.6.15-rt22-w05.03.04-g9cbaa8e3b5c6

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

error: extracting '/home/user/ptxproj/src/linux-6.6.15-rt22-w05.03.04-g9cbaa8e3b5c6.tgz' failed


ptxdist: error: failed to extract '/home/user/ptxproj/src/linux-6.6.15-rt22-w05.03.04-g9cbaa8e3b5c6.tgz'.

make: *** [/usr/local/lib/ptxdist-2020.08.0/rules/post/ptxd_make_world_extract.make:40: /home/user/ptxproj/platform-wago-pfc300/state/kernel-header.extract] Error 1

```

Thanks for your help

**Comment by falk-werner** [comment]
Hello @mm-tkr,

Thanks for your issue. Some files in our repository are too big to be stored in git. We use [git lfs](https://git-lfs.com/) to store these files. In order to make this work, git lfs must be installed before cloning the repository. You can install git lfs using the following command:

    sudo apt install git-lfs && git lfs install

Please clone the repository again after git lfs is installed. You should not encounter MD5 checksum mismatches afterwards.

**Comment by mm-tkr** [comment]
Ah yes indeed that was my fault, I seem to have skipped that part in the ReadMe when setting up.
It works fine now, thanks.
